---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testy-backend
  namespace: testy
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testy-celery
  namespace: testy
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testy-notifications
  namespace: testy
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testy-frontend
  namespace: testy
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testy-postgres
  namespace: testy
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testy-redis
  namespace: testy
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testy-pgbouncer
  namespace: testy
automountServiceAccountToken: false
